[test]
# Preload the test setup file before running tests
preload = ["./test/setup.ts"]

# Test configuration
root = "./src"

# Coverage settings
coverage = true
coverageReporter = ["text", "lcov"]
coverageDirectory = "coverage" 