services:
  postgres-test:
    image: postgres:17-alpine
    container_name: litomi-test-db
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: litomi_e2e_test
    ports:
      - '5433:5432' # Different port to avoid conflicts with local PostgreSQL
    volumes:
      - test-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U testuser -d litomi_e2e_test']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  test-db-data:
