services:
  litomi:
    image: postgres:17-alpine
    container_name: postgres-test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - '5434:5432'
    volumes:
      - test-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test_user -d test_db']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  test-db-data:
