services:
  litomi:
    image: postgres:17-alpine
    container_name: postgres-test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - '5434:5432'
    volumes:
      - test-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test_user -d test_db']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    ports:
      - '6380:6379'
    volumes:
      - redis-data:/data

  srh:
    image: hiett/serverless-redis-http:latest
    ports:
      - '8079:80'
    environment:
      SRH_MODE: env
      SRH_TOKEN: local_dev_token
      SRH_CONNECTION_STRING: 'redis://redis:6379'
    depends_on:
      - redis

volumes:
  test-db-data:
  redis-data:
