name = "image"
account_id = "$CLOUDFLARE_ACCOUNT_ID"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Optional: Add custom domain routes
# [[routes]]
# pattern = "cors.your-domain.com/*"
# zone_name = "your-domain.com"