export const mockKHentaiMangas = [
  {
    id: 1,
    archived: 1,
    blocked: 0,
    category: 1,
    current_gid: 1,
    current_key: 1,
    expunged: 0,
    filecount: 10,
    filesize: 1000,
    first_gid: 1,
    first_key: 'key1',
    parent_gid: 0,
    parent_key: '',
    posted: 1640995200,
    rating: 450,
    tags: [
      { id: 1, tag: ['other', 'ai generated'] },
      { id: 2, tag: ['female', 'big breasts'] },
      { id: 3, tag: ['language', 'korean'] },
    ],
    thumb: 'image1.jpg',
    thumb_extension: 'jpg',
    title: 'Test Manga 1',
    title_jpn: '',
    token: 'token1',
    torrentcount: 0,
    updated: 1640995200,
    uploader: 'user1',
    views: 100,
  },
  {
    id: 2,
    archived: 1,
    blocked: 0,
    category: 2,
    current_gid: 2,
    current_key: 2,
    expunged: 0,
    filecount: 20,
    filesize: 2000,
    first_gid: 2,
    first_key: 'key2',
    parent_gid: 0,
    parent_key: '',
    posted: 1640995200,
    rating: 400,
    tags: [
      { id: 4, tag: ['female', 'small breasts'] },
      { id: 5, tag: ['male', 'muscle'] },
      { id: 6, tag: ['language', 'korean'] },
    ],
    thumb: 'image2.jpg',
    thumb_extension: 'jpg',
    title: 'Test Manga 2',
    title_jpn: '',
    token: 'token2',
    torrentcount: 0,
    updated: 1640995200,
    uploader: 'user2',
    views: 200,
  },
  {
    id: 3,
    archived: 1,
    blocked: 0,
    category: 1,
    current_gid: 3,
    current_key: 3,
    expunged: 0,
    filecount: 15,
    filesize: 1500,
    first_gid: 3,
    first_key: 'key3',
    parent_gid: 0,
    parent_key: '',
    posted: 1640995200,
    rating: 420,
    tags: [
      { id: 7, tag: ['other', 'ai generated'] },
      { id: 8, tag: ['language', 'korean'] },
    ],
    thumb: 'image3.jpg',
    thumb_extension: 'jpg',
    title: 'Test Manga 3',
    title_jpn: '',
    token: 'token3',
    torrentcount: 0,
    updated: 1640995200,
    uploader: 'user3',
    views: 150,
  },
  {
    id: 4,
    archived: 1,
    blocked: 0,
    category: 1,
    current_gid: 4,
    current_key: 4,
    expunged: 0,
    filecount: 25,
    filesize: 2500,
    first_gid: 4,
    first_key: 'key4',
    parent_gid: 0,
    parent_key: '',
    posted: 1640995200,
    rating: 480,
    tags: [
      { id: 9, tag: ['parody', 'naruto'] },
      { id: 10, tag: ['character', 'sakura'] },
      { id: 11, tag: ['language', 'korean'] },
    ],
    thumb: 'image4.jpg',
    thumb_extension: 'jpg',
    title: 'Test Manga 4',
    title_jpn: '',
    token: 'token4',
    torrentcount: 0,
    updated: 1640995200,
    uploader: 'user4',
    views: 300,
  },
  {
    id: 5,
    archived: 1,
    blocked: 0,
    category: 1,
    current_gid: 5,
    current_key: 5,
    expunged: 0,
    filecount: 30,
    filesize: 3000,
    first_gid: 5,
    first_key: 'key5',
    parent_gid: 0,
    parent_key: '',
    posted: 1640995200,
    rating: 460,
    tags: [
      { id: 12, tag: ['male', 'muscle'] },
      { id: 13, tag: ['other', 'full color'] },
      { id: 14, tag: ['language', 'korean'] },
    ],
    thumb: 'image5.jpg',
    thumb_extension: 'jpg',
    title: 'Test Manga 5',
    title_jpn: '',
    token: 'token5',
    torrentcount: 0,
    updated: 1640995200,
    uploader: 'user5',
    views: 250,
  },
]
