name: Database Backup

on:
  schedule:
    # Run daily at 6 AM KST
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Generate date
        id: date
        run: echo "date=$(date +%Y%m%d-%H%M)" >> $GITHUB_OUTPUT

      - name: Install PostgreSQL
        run: |
          sudo apt update
          sudo apt install -y postgresql

      - name: Create backup
        env:
          POSTGRES_URL_DIRECT: ${{ secrets.POSTGRES_URL_DIRECT }}
          DATE: ${{ steps.date.outputs.date }}
          BACKUP_ENCRYPTION_KEY: ${{ secrets.BACKUP_ENCRYPTION_KEY }}
          BACKUP_PREFIX: 'litomi'
          BACKUP_DIR: 'backups'
        run: |
          FILENAME="${BACKUP_PREFIX}-${DATE}"
          DUMP_FILE="${BACKUP_DIR}/${FILENAME}.dump"
          ENCRYPTED_FILE="${BACKUP_DIR}/${FILENAME}.dump.gpg"
          mkdir -p "${BACKUP_DIR}"

          # Create compressed backup
          pg_dump "$POSTGRES_URL_DIRECT" \
            --no-owner \
            --no-privileges \
            --no-comments \
            --format=custom \
            --compress=9 \
            --file="${DUMP_FILE}"

          # Encrypt the backup using GPG with symmetric encryption
          gpg --batch --yes \
            --passphrase="$BACKUP_ENCRYPTION_KEY" \
            --cipher-algo AES256 \
            --symmetric \
            --output "${ENCRYPTED_FILE}" \
            "${DUMP_FILE}"

          rm "${DUMP_FILE}"
          sha256sum "${ENCRYPTED_FILE}" > "${ENCRYPTED_FILE}.sha256"

          # Display backup info
          ls -lh "${BACKUP_DIR}/"

      - name: Upload to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BACKUP_PREFIX }}-backup-${{ steps.date.outputs.date }}
          path: ${{ env.BACKUP_DIR }}/
          retention-days: 30
        env:
          BACKUP_PREFIX: 'litomi'
          BACKUP_DIR: 'backups'
